---
title: "An approach to using Vega in R Markdown"
output:
  html_document:
    includes:
      in_header: includes/header.html
    self_contained: false
    mathjax: null
    lib_dir: vendor
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

str_lcfirst <- function(str) {
  gsub("(^[[:alnum:]]{0,1})", "\\L\\1", str, perl = TRUE)
}

str_pascal_case <- function(str) {
  gsub("(^|[^[:alnum:]])([[:alnum:]])", "\\U\\2", str, perl = TRUE)
}

str_camel_case <- function(str) {
  str_lcfirst(str_pascal_case(str))
}
```

```{r add_theme, results = "asis"}
library("jsonlite")

# Load Vega theme config
theme <- fromJSON("theme.json")

# Declare global JS var for Vega theme
cat(paste('<script>var theme = ', toJSON(theme, auto_unbox = TRUE), ';</script>', sep = ""))
```

```{r add_data, results = "asis"}
library("jsonlite")
library("purrr", warn.conflicts = FALSE)

# Use iris dataset, rename columns for JS
data = iris %>%
  set_names(~ str_camel_case(.))

# Declare global JS var for Vega data
cat(paste('<script>var data = ', toJSON(data), ';</script>', sep = ""))
```

<div id="scatterplot"></div>

```{js render_scatterplot}
// Generate Vega-Lite spec
var spec = finch
  .vl(data)
  .config(theme)
  .circle()
  .x('petalLength')
  .y('sepalLength')
  .color('species', 'nominal')
  .spec;

// Declare Vega embed config
var opts = {
  actions: false,
  renderer: 'canvas'
};

// Embed visualisation
vegaEmbed('#scatterplot', spec, opts);
```

<div id="faceted-plot"></div>

```{js render_faceted_plot}
var spec = finch
  .vl(data)
  .config(theme)
  .width(150)
  .height(150)
  .bar()
  .x('sepalLength', 'q', {
    bin: true,
    title: 'sepalLength'
  })
  .y(null, 'q', {aggregate: 'count', title: 'count'})
  .tooltip(null, 'q', {aggregate: 'count'})
  .column('species', 'n')
  .spec;

vegaEmbed('#faceted-plot', spec, {actions: false});
```

<div id="repeated-plot"></div>

```{js render_repeated_plot}
var spec = finch
  .vl(data)
  .config(theme)
  .repeat(
    {
      row: ['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth'],
      column: ['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth']
    },
    finch
      .vl()
      .width(100)
      .height(100)
      .circle()
      .x({repeat: 'column'}, 'q')
      .y({repeat: 'row'}, 'q')
      .color('species', 'n')
  ).spec;

vegaEmbed('#repeated-plot', spec, {actions: false});
```

<div id="polynomial-fit"></div>

```{js render_polynomial_fit}
// Fit data to polynomial curve
var fitData = regression
  .polynomial(
    data.map(function(d) {
      return [d.petalLength, d.sepalLength];
    })
  )
  .points.map(function(d) {
    return {x: d[0], y: d[1]};
  });

var spec = finch
  .vl()
  .config(theme)
  .layer(
    finch
      .vl(data)
      .circle()
      .x('petalLength')
      .y('sepalLength')
      .color(null, null, {value: 'blue'}),
    finch
      .vl(fitData)
      .line()
      .x('x', null, {axis: null})
      .y('y', null, {axis: null})
      .color(null, null, {value: 'red'})
  )
  .tooltip([
    {field: 'petalLength', type: 'q'},
    {field: 'sepalLength', type: 'q'}
  ])
  .spec;

vegaEmbed('#polynomial-fit', spec, {actions: false});
```
